//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librainian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Librainian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please direct me to a folder..
        /// </summary>
        internal static string _Please_direct_me_to_a_folder_ {
            get {
                return ResourceManager.GetString("_Please_direct_me_to_a_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout is less than one..
        /// </summary>
        internal static string Database_GetConnection_Timeout_is_less_than_one_ {
            get {
                return ResourceManager.GetString("Database_GetConnection_Timeout_is_less_than_one_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of range.
        /// </summary>
        internal static string Out_of_range {
            get {
                return ResourceManager.GetString("Out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxValue must be &gt;= minValue.
        /// </summary>
        internal static string SafeRandom_Next_ {
            get {
                return ResourceManager.GetString("SafeRandom_Next_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxValue must be greater than or equal to zero..
        /// </summary>
        internal static string SafeRandom_Next_maxValue_must_be_greater_than_or_equal_to_zero_ {
            get {
                return ResourceManager.GetString("SafeRandom_Next_maxValue_must_be_greater_than_or_equal_to_zero_", resourceCulture);
            }
        }
    }
}
